import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../../providers";
import ToasterClient from "../components/ToasterClient";
import Script from "next/script";
import Snow from '../components/Snow';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <Providers>
          {children}
          <ToasterClient />
        
        </Providers>
      </body>
    </html>
  );
}
